### ISSUE TITLE
Error: malformed BED entry at line XXXX. Start Coordinate detected that is < 0. Exiting.

### ISSUE THREAD

**Issue by suhrig** [Genomon-Project/GenomonSplicingMutation#3]
Hi Yuichi,

SAVNet crashes on some samples, because the BED file `output.SJ_merged.annot.txt.tmp1.junc1.exon.bed` contains negative values. Here is an example of an offending line:

```
MT      -3      58      MT,29,11767
```

I was able to solve the error by removing lines in the junction files generated by STAR concerning the MT chromosome, but you might want to fix the underlying bug, since theoretically it could happen on interesting chromosomes as well.

Here is the full error stack trace:

```
savnet --keep_annotated sample_sheet.tsv output
07/17/2019 11:05:55 - savnet.run - INFO - Merging mutation data.
07/17/2019 11:05:56 - savnet.run - INFO - Merging splicing junction data.
07/17/2019 11:07:20 - savnet.run - INFO - Adding annotation to splicing junction data.
Error: malformed BED entry at line 858144. Start Coordinate detected that is < 0. Exiting.
Traceback (most recent call last):
  File "/software/savnet/bin/junc_utils", line 10, in <module>
    sys.exit(main())
  File "/software/savnet/lib/python3.6/site-packages/junc_utils/__init__.py", line 13, in main
    args.func(args)
  File "/software/savnet/lib/python3.6/site-packages/junc_utils/run.py", line 26, in annotate_main
    annotate.annot_junction(args.junc_file, args.output_path, args.junction_margin, args.exon_margin, args.genome_id, is_grc)
  File "/software/savnet/lib/python3.6/site-packages/junc_utils/annotate.py", line 75, in annot_junction
    subprocess.check_call(["bedtools", "intersect", "-a", output_file + ".tmp1.junc1.exon.bed", "-b", output_file + ".tmp.refExon.bed.gz", "-loj"], stdout = hout_e1)
  File "/software/python/python-3.6.1/el7/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bedtools', 'intersect', '-a', 'output.SJ_merged.annot.txt.tmp1.junc1.exon.bed', '-b', 'output.SJ_merged.annot.txt.tmp.refExon.bed.gz', '-loj']' returned non-zero exit status 1.
07/17/2019 11:08:23 - savnet.run - INFO - Checking association betweeen mutation and splicing junction data.
Traceback (most recent call last):
  File "/software/savnet/bin/junc_utils", line 10, in <module>
    sys.exit(main())
  File "/software/savnet/lib/python3.6/site-packages/junc_utils/__init__.py", line 13, in main
    args.func(args)
  File "/software/savnet/lib/python3.6/site-packages/junc_utils/run.py", line 49, in associate_main
    is_grc = grc_check(args.annotated_junction_file, [0])
  File "/software/savnet/lib/python3.6/site-packages/annot_utils/utils.py", line 48, in grc_check
    hin = open(input_file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'output.SJ_merged.annot.txt'
Traceback (most recent call last):
  File "/software/savnet/bin/savnet", line 10, in <module>
    sys.exit(main())
  File "/software/savnet/lib/python3.6/site-packages/savnet/__init__.py", line 10, in main
    savnet_main(args)
  File "/software/savnet/lib/python3.6/site-packages/savnet/run.py", line 69, in savnet_main
    subprocess.check_call(associate_commands)
  File "/software/python/python-3.6.1/el7/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['junc_utils', 'associate', 'output.SJ_merged.annot.txt', 'output.mut_merged.vcf', 'output.SJ_merged.associate.txt', '--donor_size', '3,6', '--acceptor_size', '6,1', '--genome_id', 'hg19']' returned non-zero exit status 1.
```

Regards,
Sebastian

**Comment by friend1ws** [comment]
Thank you for the feedback! I will try to fix that error soon.

**Comment by yasunorikogure** [comment]
Hi Shiraishi-sensei,

The same error is occurring in my analysis so I thought I'd share this with you.
I applied the same method as suhrig -- removing MT records in SJ -- and worked well.

Thank you!

```
06/02/2020 12:29:05 - savnet.run - WARNING - --grc argument is deprecated and ignored.
06/02/2020 12:29:05 - savnet.run - INFO - Merging mutation data.
06/02/2020 12:36:26 - savnet.run - INFO - Merging splicing junction data.
06/02/2020 12:38:04 - savnet.run - INFO - Adding annotation to splicing junction data.
Error: Invalid record in file ./output/sanvet_output.SJ_merged.annot.txt.tmp1.junc1.exon.bed. Record is 
MT	-3	58	MT,29,16282
```

**Comment by cpreviti** [comment]
Hi there,
I came across this error as well...but it was on chromosome 17...which I can't just remove. 
Do you have any idea if you could fix this soon? Are you still developing SAVnet?
This issue has been around for more than a year...if you need help/feedback please let me know.

**Comment by friend1ws** [comment]
@cpreviti, Thank you very much for your interest in SAVNet.
Yes, we are still actively working on projects related to this package.
Could you please tell me which version of junc_utils you are using?
```
$ junc_utils --version
```

The latest version is 0.5.1. So if your package is older than that, please update it.
```
python -m pip install junc_utils==0.5.1 --user 
```

If this does not solve the problem, could you please post the error message?

Thank you very much.
